/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedTeamRouteImport } from './routes/_protected/team'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as ApiV1TeamRouteImport } from './routes/api/v1/team'
import { Route as ApiWebhooksFedapayRouteImport } from './routes/api/webhooks/fedapay'
import { Route as ApiWebhooksKkiapayRouteImport } from './routes/api/webhooks/kkiapay'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiV1ProjectsIdRouteImport } from './routes/api/v1/projects.$id'
import { Route as ApiV1TeamInvitationsRouteImport } from './routes/api/v1/team.invitations'
import { Route as ApiV1TeamMembersIdRouteImport } from './routes/api/v1/team.members.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamRoute = ProtectedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TeamRoute = ApiV1TeamRouteImport.update({
  id: '/api/v1/team',
  path: '/api/v1/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFedapayRoute = ApiWebhooksFedapayRouteImport.update({
  id: '/api/webhooks/fedapay',
  path: '/api/webhooks/fedapay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksKkiapayRoute = ApiWebhooksKkiapayRouteImport.update({
  id: '/api/webhooks/kkiapay',
  path: '/api/webhooks/kkiapay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsIdRoute = ApiV1ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ProjectsRoute,
} as any)
const ApiV1TeamInvitationsRoute = ApiV1TeamInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => ApiV1TeamRoute,
} as any)
const ApiV1TeamMembersIdRoute = ApiV1TeamMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => ApiV1TeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/team': typeof ApiV1TeamRouteWithChildren
  '/api/webhooks/fedapay': typeof ApiWebhooksFedapayRoute
  '/api/webhooks/kkiapay': typeof ApiWebhooksKkiapayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRoute
  '/api/v1/team/invitations': typeof ApiV1TeamInvitationsRoute
  '/api/v1/team/members/$id': typeof ApiV1TeamMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/team': typeof ProtectedTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/team': typeof ApiV1TeamRouteWithChildren
  '/api/webhooks/fedapay': typeof ApiWebhooksFedapayRoute
  '/api/webhooks/kkiapay': typeof ApiWebhooksKkiapayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRoute
  '/api/v1/team/invitations': typeof ApiV1TeamInvitationsRoute
  '/api/v1/team/members/$id': typeof ApiV1TeamMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signup': typeof SignupRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/team': typeof ProtectedTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/team': typeof ApiV1TeamRouteWithChildren
  '/api/webhooks/fedapay': typeof ApiWebhooksFedapayRoute
  '/api/webhooks/kkiapay': typeof ApiWebhooksKkiapayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRoute
  '/api/v1/team/invitations': typeof ApiV1TeamInvitationsRoute
  '/api/v1/team/members/$id': typeof ApiV1TeamMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/team'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/api/v1/team'
    | '/api/webhooks/fedapay'
    | '/api/webhooks/kkiapay'
    | '/api/webhooks/stripe'
    | '/api/v1/projects/$id'
    | '/api/v1/team/invitations'
    | '/api/v1/team/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/team'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/api/v1/team'
    | '/api/webhooks/fedapay'
    | '/api/webhooks/kkiapay'
    | '/api/webhooks/stripe'
    | '/api/v1/projects/$id'
    | '/api/v1/team/invitations'
    | '/api/v1/team/members/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/select-organization'
    | '/signup'
    | '/_protected/admin'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/_protected/team'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/api/v1/team'
    | '/api/webhooks/fedapay'
    | '/api/webhooks/kkiapay'
    | '/api/webhooks/stripe'
    | '/api/v1/projects/$id'
    | '/api/v1/team/invitations'
    | '/api/v1/team/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRouteWithChildren
  ApiV1TeamRoute: typeof ApiV1TeamRouteWithChildren
  ApiWebhooksFedapayRoute: typeof ApiWebhooksFedapayRoute
  ApiWebhooksKkiapayRoute: typeof ApiWebhooksKkiapayRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/team': {
      id: '/_protected/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ProtectedTeamRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/team': {
      id: '/api/v1/team'
      path: '/api/v1/team'
      fullPath: '/api/v1/team'
      preLoaderRoute: typeof ApiV1TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/fedapay': {
      id: '/api/webhooks/fedapay'
      path: '/api/webhooks/fedapay'
      fullPath: '/api/webhooks/fedapay'
      preLoaderRoute: typeof ApiWebhooksFedapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/kkiapay': {
      id: '/api/webhooks/kkiapay'
      path: '/api/webhooks/kkiapay'
      fullPath: '/api/webhooks/kkiapay'
      preLoaderRoute: typeof ApiWebhooksKkiapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$id': {
      id: '/api/v1/projects/$id'
      path: '/$id'
      fullPath: '/api/v1/projects/$id'
      preLoaderRoute: typeof ApiV1ProjectsIdRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/team/invitations': {
      id: '/api/v1/team/invitations'
      path: '/invitations'
      fullPath: '/api/v1/team/invitations'
      preLoaderRoute: typeof ApiV1TeamInvitationsRouteImport
      parentRoute: typeof ApiV1TeamRoute
    }
    '/api/v1/team/members/$id': {
      id: '/api/v1/team/members/$id'
      path: '/members/$id'
      fullPath: '/api/v1/team/members/$id'
      preLoaderRoute: typeof ApiV1TeamMembersIdRouteImport
      parentRoute: typeof ApiV1TeamRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTeamRoute: typeof ProtectedTeamRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTeamRoute: ProtectedTeamRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiV1ProjectsRouteChildren {
  ApiV1ProjectsIdRoute: typeof ApiV1ProjectsIdRoute
}

const ApiV1ProjectsRouteChildren: ApiV1ProjectsRouteChildren = {
  ApiV1ProjectsIdRoute: ApiV1ProjectsIdRoute,
}

const ApiV1ProjectsRouteWithChildren = ApiV1ProjectsRoute._addFileChildren(
  ApiV1ProjectsRouteChildren,
)

interface ApiV1TeamRouteChildren {
  ApiV1TeamInvitationsRoute: typeof ApiV1TeamInvitationsRoute
  ApiV1TeamMembersIdRoute: typeof ApiV1TeamMembersIdRoute
}

const ApiV1TeamRouteChildren: ApiV1TeamRouteChildren = {
  ApiV1TeamInvitationsRoute: ApiV1TeamInvitationsRoute,
  ApiV1TeamMembersIdRoute: ApiV1TeamMembersIdRoute,
}

const ApiV1TeamRouteWithChildren = ApiV1TeamRoute._addFileChildren(
  ApiV1TeamRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRouteWithChildren,
  ApiV1TeamRoute: ApiV1TeamRouteWithChildren,
  ApiWebhooksFedapayRoute: ApiWebhooksFedapayRoute,
  ApiWebhooksKkiapayRoute: ApiWebhooksKkiapayRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
